# Generated by Django 3.2.14 on 2022-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
    ]
